export interface Property {
    id: number;
    name: string;
    location: string;
    priceRange: string;
    bedrooms: string;
    bathrooms: string;
    area: string;
    image: string;
    description: string;
    type: string;
    status: string;
    features: string[];
    amenities: string[];
    gallery: string[];
}

export const properties: Property[] = [
    {
        id: 1,
        name: 'Sunnyvale 2',
        location: 'Sta. Ignacia, Tarlac',
        priceRange: '₱850,000 - ₱2,200,000',
        bedrooms: '1 - 3',
        bathrooms: '1 - 2',
        area: '40 - 80 sqm',
        image: 'https://smdc.com/content/webp-express/webp-images/doc-root/content/uploads/2024/09/Clubhouse_1920x1080px-768x432.jpg.webp',
        description: 'A serene community offering affordable housing options in Tarlac.',
        type: 'House and Lot',
        status: 'Pre-selling',
        features: [
            'Gated community',
            '24/7 security',
            'Landscaped parks',
            'Community center',
        ],
        amenities: ['Clubhouse', 'Playground', 'Basketball court', 'Swimming pool'],
        gallery: Array(6).fill('https://smdc-philippines.com/wp-content/uploads/2019/07/air_amenities-7-2.jpg'),
    },
    {
        id: 2,
        name: 'Amorrosa Residences',
        location: 'Santo Tomas, Batangas',
        priceRange: '₱1,650,000 - ₱1,700,000',
        bedrooms: '2 - 3',
        bathrooms: '1 - 2',
        area: '50 - 100 sqm',
        image: 'https://smdc.com/content/webp-express/webp-images/doc-root/content/uploads/2024/02/Amorrosa-Clubhouse-768x768.jpg.webp',
        description: 'A charming residential community nestled in the heart of Batangas.',
        type: 'House and Lot',
        status: 'Pre-selling',
        features: [
            'Gated entrance',
            '24/7 security',
            'Wide roads',
            'Underground drainage system',
        ],
        amenities: ['Clubhouse', 'Swimming pool', 'Children’s playground', 'Basketball court'],
        gallery: Array(6).fill('https://smdc-philippines.com/wp-content/uploads/2019/07/air_amenities-7-2.jpg'),
    },
    {
        id: 3,
        name: 'Parkville',
        location: 'Bacolod City',
        priceRange: '₱2,700,000 - ₱4,300,000',
        bedrooms: '2 - 4',
        bathrooms: '2 - 3',
        area: '60 - 120 sqm',
        image: 'https://smdc.com/content/webp-express/webp-images/doc-root/content/uploads/2023/12/Parkville-Hero-768x768.jpg.webp',
        description: 'A modern community designed with thematic nature parks in Bacolod City.',
        type: 'House and Lot',
        status: 'Pre-selling',
        features: [
            'Thematic parks',
            'Gated community',
            '24/7 security',
            'Concrete roads and sidewalks',
        ],
        amenities: ['Clubhouse', 'Swimming pool', 'Playground', 'Jogging paths'],
        gallery: Array(6).fill('https://smdc-philippines.com/wp-content/uploads/2019/07/air_amenities-7-2.jpg'),
    },
    {
        id: 4,
        name: 'Turf Residences',
        location: 'Biñan City, Laguna',
        priceRange: '₱2,500,000 - ₱3,300,000',
        bedrooms: '1 - 3',
        bathrooms: '1 - 2',
        area: '45 - 95 sqm',
        image: 'https://smdc.com/content/webp-express/webp-images/doc-root/content/uploads/2023/11/Turf-ListingIcon-768x768.jpg.webp',
        description: 'A vibrant garden community connecting you to the best of life in Laguna.',
        type: 'House and Lot',
        status: 'Pre-selling',
        features: [
            'Gated entrance',
            '24/7 security',
            'Landscaped gardens',
            'Wide roads',
        ],
        amenities: ['Clubhouse', 'Swimming pool', 'Basketball court', 'Children’s play area'],
        gallery: Array(6).fill('https://smdc-philippines.com/wp-content/uploads/2019/07/air_amenities-7-2.jpg'),
    },
    {
        id: 5,
        name: 'SMDC Jade Residences',
        location: 'Chino Roces Ave., Brgy. Bangkal, Makati City',
        priceRange: '₱6,311,000 - ₱12,264,000',
        bedrooms: 'Studio to 2-Bedroom Units',
        bathrooms: '1 to 2',
        area: 'Varies per unit',
        image: 'https://smdc.com/content/webp-express/webp-images/doc-root/content/uploads/2023/06/Jade-Facade-768x768.jpg.webp',
        description: 'Effortlessly elegant lifestyle within the vibrant district of Chino Roces Avenue.',
        type: 'Condominium',
        status: 'Pre-selling',
        features: [
            'Grand lobby',
            '24/7 security',
            'Backup power',
            'Parking space',
            'Retail areas',
        ],
        amenities: [
            'Swimming Pool',
            'Fitness Center',
            'Function Rooms',
            'Children’s Play Area',
            'Lounge Areas',
        ],
        gallery: Array(6).fill('https://smdc-philippines.com/wp-content/uploads/2019/07/air_amenities-7-2.jpg'),
    },
    {
        id: 6,
        name: 'Bloom Residences',
        location: 'Parañaque',
        priceRange: '₱4,000,000 - ₱6,600,000',
        bedrooms: '2 - 3',
        bathrooms: '1 - 2',
        area: '50 - 90 sqm',
        image: 'https://smdc.com/content/webp-express/webp-images/doc-root/content/uploads/2020/06/image-180-13-768x760.jpg.webp',
        description: 'A fresh take on urban living with its modern design and lush landscapes.',
        type: 'Condominium',
        status: 'Ready for Occupancy / Pre-selling',
        features: [
            'Grand lobby',
            '24/7 security',
            'Backup power',
            'Parking space',
            'Retail areas',
        ],
        amenities: [
            'Swimming Pool',
            'Fitness Center',
            'Function Rooms',
            'Children’s Play Area',
            'Jogging Path',
        ],
        gallery: Array(6).fill('https://smdc-philippines.com/wp-content/uploads/2019/07/air_amenities-7-2.jpg'),
    },
    {
        id: 7,
        name: 'Hill Residences',
        location: 'Novaliches, Quezon City',
        priceRange: '₱3,100,000 - ₱3,800,000',
        bedrooms: '1 - 2',
        bathrooms: '1 - 2',
        area: '30 - 65 sqm',
        image: 'https://smdc.com/content/webp-express/webp-images/doc-root/content/uploads/2023/05/image-180-4-scaled-converted-768x760.jpg.webp',
        description: 'A private community situated on a hilltop, offering a serene environment.',
        type: 'Condominium',
        status: 'Ready for Occupancy / Pre-selling',
        features: [
            'Gated community',
            '24/7 security',
            'Backup power',
            'Parking space',
            'Retail areas',
        ],
        amenities: [
            'Swimming Pool',
            'Function Hall',
            'Children’s Play Area',
            'Basketball Court',
            'Landscaped Areas',
        ],
        gallery: Array(6).fill('https://smdc-philippines.com/wp-content/uploads/2019/07/air_amenities-7-2.jpg'),
    },
    {
        id: 8,
        name: 'Sail Residences',
        location: 'Pasay City',
        priceRange: '₱8,600,000 - ₱24,600,000',
        bedrooms: '1 - 3',
        bathrooms: '1 - 3',
        area: '50 - 150 sqm',
        image: 'https://smdc.com/content/webp-express/webp-images/doc-root/content/uploads/2019/03/Sail-Thumbnailv2-768x760.jpg.webp',
        description: 'The gem of the Mall of Asia district, inspired by international seaside resorts.',
        type: 'Condominium',
        status: 'Pre-selling',
        features: [
            'Grand lobby',
            '24/7 security',
            'Backup power',
            'Parking space',
            'Retail areas',
        ],
        amenities: [
            'Swimming Pools',
            'Cabanas',
            'Al Fresco Lounge',
            'Chillscape Lounge',
            'Multi-Function Areas',
            'Zen Park',
            'Jogging Path',
            'Children’s Play Area',
        ],
        gallery: Array(6).fill('https://smdc-philippines.com/wp-content/uploads/2019/07/air_amenities-7-2.jpg'),
    },
    {
        id: 9,
        name: 'Red Residences',
        location: 'Chino Roces, Makati',
        priceRange: '₱6,500,000 - ₱15,200,000',
        bedrooms: 'Studio to 2',
        bathrooms: '1 - 2',
        area: '25 - 90 sqm',
        image: 'https://smdc.com/content/webp-express/webp-images/doc-root/content/uploads/2023/05/RED-Facade_383x350px-1107-768x590.jpg.webp',
        description: 'A trendy, stylish living space in the heart of the Makati Central Business District.',
        type: 'Condominium',
        status: 'Ready for Occupancy / Pre-selling',
        features: [
            'Grand lobby',
            '24/7 security',
            'Backup power',
            'Parking space',
            'Retail areas',
        ],
        amenities: [
            'Swimming Pool',
            'Fitness Center',
            'Function Rooms',
            'Sky Lounge',
            'Landscaped Gardens',
        ],
        gallery: Array(6).fill('https://smdc-philippines.com/wp-content/uploads/2019/07/air_amenities-7-2.jpg'),
    },
    {
        id: 10,
        name: 'Gold Residences',
        location: 'Parañaque City',
        priceRange: '₱6,800,000 - ₱15,700,000',
        bedrooms: '1 - 2',
        bathrooms: '1 - 2',
        area: '45 - 90 sqm',
        image: 'https://smdc.com/content/uploads/2020/06/image-180-18-768x760.jpg',
        description: 'SMDC’s first township, exemplifying the gold standard in modern living.',
        type: 'Condominium',
        status: 'Pre-selling',
        features: [
            'Grand lobby',
            '24/7 security',
            'Backup power',
            'Parking space',
            'Retail areas',
        ],
        amenities: [
            'Swimming Pool',
            'Fitness Center',
            'Function Rooms',
            'Children’s Play Area',
            'Lush Gardens',
            'Jogging Path',
        ],
        gallery: Array(6).fill('https://smdc-philippines.com/wp-content/uploads/2019/07/air_amenities-7-2.jpg'),
    },
];